---
title: "add audio to acc 2017"
output: html_document
---

# load libraries
```{r}
library(tidyverse)
library(bcpa)
library(tidyr)
library(data.table)
library(lubridate)
library(janitor)
library(ggplot2)
require(PBSmapping)
library(vroom)
op <- options(digits.secs=3)
```

### read audio data
```{r}
load("/Users/Edward/Dropbox/Vivesi2018/Analysis/Audio/Mviv17_60_calls.robj")
Mv18_summary$Local_Time <- Mv18_summary$time -7*3600

Mv18_main$time <- rep(ymd_hms("2020-01-01 00:00:00.000"), length(Mv18_main$file))

for(i in 1:length(Mv18_main$file)){
  split <- NA
  hour <- NA 
  min <- NA
  sec <- NA
  end <- NA
  part <- NA
  
  split <- strsplit(Mv18_main$file[i], split = "_")
  year <- 2017
  month <- as.numeric(split[[1]][2])
  day <- as.numeric(split[[1]][3])
  hour <- as.numeric(split[[1]][4])
  min <- as.numeric(split[[1]][5])
  sec <- as.numeric(split[[1]][6])
  
  Mv18_main$time[i] <- 
    ymd(paste0(year,"-",month, "-", day))+hours(hour)+minutes(min)+
    seconds(sec)
}
Mv18_main$Local_Time <- Mv18_main$time -7*3600

with(Mv18_summary, plot(time-7*3600, echo, col = 2))
with(Mv18_summary, points(time-7*3600, echo/10+15, col = "orange"))
with(Mv18_summary, points(time-7*3600, buzz*3, col = 2))

Mv18_summary$time[1]
```


# load latest ACC data
```{r}
m17_60 <- read.csv("C:/Users/Edward/Dropbox/VivesiACC/data/clean/clean_ACC_Mviv17_60.csv")
m17_60$datetime <- as.POSIXct(m17_60$time, format = "%Y-%m-%d %H:%M:%OS", tz = "UTC")

```

## add echo to acc
```{r}
m17_60$call <- 0
i = 1
for(i in 1:nrow(Mv18_main)){
  start_idx <- which.min(abs((m17_60$datetime)-(Mv18_main$Local_Time[i]+
                               Mv18_main$start_time[i])))
  end_idx <- which.min(abs((m17_60$datetime) -(Mv18_main$Local_Time[i]+
                                           Mv18_main$start_time[i]+
                                           Mv18_main$duration[i])))
  # Mv18_main$Local_Time[i]+Mv18_main$start_time[i]
  # m17_60$datetime[1]
  m17_60$call[start_idx:end_idx] <- 1
}

which(m17_60$call == 1)

tail(Mv18_main)
range(Mv18_main$Local_Time)
range(m17_60$datetime)
m17_60$datetime[start_idx]
```

## get buzz times
```{r}

```


## add buzz to acc
```{r}
m17_60$buzz <- 0
i = 1
for(i in 1:length(buzz_times)){
  idx <- which.min(abs(m17_60$datetime-(buzz_times[i])))
  m17_60$buzz[idx:(idx+25)] <- 1
}

with(m17_60, plot(datetime, buzz))
with(m17_60[499000:500000,], 
     plot(datetime, Accelerometer.X, col = call+buzz+1, cex = call+buzz+1/2,  type = "o", pch = 16))

```

# save data
```{r}
save(m17_60, Mv18_main, Mv18_buzz, Mv18_cons, Mviv18, Mv18_summary, 
     file = "/Users/Edward/Dropbox/Vivesi2018/Analysis/Accelerometer/data/Mviv18_06_complete.robj")
load("/Users/Edward/Dropbox/Vivesi2018/Analysis/Accelerometer/data/Mviv18_06_complete.robj")

```

# write csv
```{r}
write.csv(m18_06, file = "Mviv18_06_ACC_Call.csv")
```

