---
title: "add audio to acc 2017"
output: html_document
---

# load libraries
```{r}
library(tidyverse)
library(bcpa)
library(tidyr)
library(data.table)
library(lubridate)
library(janitor)
library(ggplot2)
require(PBSmapping)
library(vroom)
library(zoo)
op <- options(digits.secs=3)
```

### read audio data
```{r}
load("../../../../Dropbox/Vivesi2018/Analysis/Audio/Mviv17_60_calls.robj")
Mv18_summary$Local_Time <- Mv18_summary$time -7*3600

Mv18_main$time <- rep(ymd_hms("2020-01-01 00:00:00.000"), length(Mv18_main$file))

for(i in 1:length(Mv18_main$file)){
  split <- NA
  hour <- NA 
  min <- NA
  sec <- NA
  end <- NA
  part <- NA
  
  split <- strsplit(Mv18_main$file[i], split = "_")
  year <- 2017
  month <- as.numeric(split[[1]][2])
  day <- as.numeric(split[[1]][3])
  hour <- as.numeric(split[[1]][4])
  min <- as.numeric(split[[1]][5])
  sec <- as.numeric(split[[1]][6])
  
  Mv18_main$time[i] <- 
    ymd(paste0(year,"-",month, "-", day))+hours(hour)+minutes(min)+
    seconds(sec)
}
Mv18_main$Local_Time <- Mv18_main$time -7*3600

with(Mv18_summary, plot(time-7*3600, echo, col = 2))
with(Mv18_summary, points(time-7*3600, echo/10+15, col = "orange"))
with(Mv18_summary, points(time-7*3600, buzz*3, col = 2))

Mv18_summary$time[1]

Mv18_main <- read.csv("../../../../Dropbox/VivesiACC/data/Audio/Mv17_60_main_calls_avisoft.csv")
Mv18_main$time <- ymd_hms(Mv18_main$time)
```


```{r}
Mv18 <- Mv18_main#[1:100000,]

Mv18 <- Mv18 %>% mutate(ints = cut(start_time, breaks = seq(0,40, by = 0.5), 
                           include.lowest = TRUE, labels = FALSE)) 
Mv18 %>% group_by(time, file, ints) %>% 
  dplyr::summarise(duration = mean(duration),
            interval = mean(interval, na.rm = TRUE),
            start_amp = mean(start_amp),
            peak_amp = mean(peak_amp),
            end_amp = mean(end_amp),
            calls = length(file)) -> Mv18_ints
  
plot(Mv18_ints$time, Mv18_ints$calls)
plot(Mv18_ints$start_amp)
plot(Mv18_ints$peak_amp)
plot(Mv18_ints$end_amp)
plot(Mv18_ints$duration)
plot(Mv18_ints$interval, ylim = c(0,1))

Mv18_ints <- Mv18_ints %>% mutate(behav = ifelse(duration > 0.008 & calls < 6 & 
                                                   peak_amp > -5 & interval > 0.1, 
                                                 "forage", "commute"))

plot(Mv18_ints$time, Mv18_ints$calls, col = as.numeric(as.factor(Mv18_ints$behav)))
plot(Mv18_ints$duration, col = as.numeric(as.factor(Mv18_ints$behav)))
plot(Mv18_ints$peak_amp, col = as.numeric(as.factor(Mv18_ints$behav)))
plot(Mv18_ints$interval, ylim = c(0,1), col = as.numeric(as.factor(Mv18_ints$behav)))

rle(Mv18_ints$behav)


plot(Mv18_ints$time-7*3600, rollmean(Mv18_ints$interval, k = 20, na.pad = TRUE), 
     # type = "o", 
     ylim = c(0,1), col = as.numeric(as.factor(Mv18_ints$behav)),
     cex = 0.2)
```

# buzz audio snippets
```{r}
buzz_files <- list.files("../../../../Dropbox/VivesiAudio/BuzzCheck/Mviv17/Mviv17_60/Buzz")
buzz_times <- data.frame(start_time, end_time, filename = buzz_files)

for(i in 1:length(Mv18_main$file)){
  split <- NA
  hour <- NA 
  min <- NA
  sec <- NA
  end <- NA
  part <- NA
  
  split <- strsplit(Mv18_main$file[i], split = "_")
  year <- 2017
  month <- as.numeric(split[[1]][2])
  day <- as.numeric(split[[1]][3])
  hour <- as.numeric(split[[1]][4])
  min <- as.numeric(split[[1]][5])
  sec <- as.numeric(split[[1]][6])
  
  Mv18_main$time[i] <- 
    ymd(paste0(year,"-",month, "-", day))+hours(hour)+minutes(min)+
    seconds(sec)
}

```

# roost audio snippets
```{r}
roost_files <- 1:4800

set.seed(1)
round(runif(min = 0, max = length(roost_files), n = 2100), 0) %>% unique()


```





# load latest ACC data
```{r}
m17_60 <- read.csv("C:/Users/Edward/Dropbox/VivesiACC/data/clean/clean_ACC_Mviv17_60.csv")
m17_60$datetime <- as.POSIXct(m17_60$time, format = "%Y-%m-%d %H:%M:%OS", tz = "UTC")

```

## add echo to acc
```{r}
m17_60$call <- 0
i = 1
for(i in 1:nrow(Mv18_main)){
  start_idx <- which.min(abs((m17_60$datetime)-(Mv18_main$Local_Time[i]+
                               Mv18_main$start_time[i])))
  end_idx <- which.min(abs((m17_60$datetime) -(Mv18_main$Local_Time[i]+
                                           Mv18_main$start_time[i]+
                                           Mv18_main$duration[i])))
  # Mv18_main$Local_Time[i]+Mv18_main$start_time[i]
  # m17_60$datetime[1]
  m17_60$call[start_idx:end_idx] <- 1
}

which(m17_60$call == 1)

tail(Mv18_main)
range(Mv18_main$Local_Time)
range(m17_60$datetime)
m17_60$datetime[start_idx]
```

## get buzz times
```{r}
spec <- "C:/Users/Edward/Dropbox/VivesiAudio/BuzzCheck/Mviv17/Mviv17_60/buzz/"
files <- list.files(path = spec)

buzz_times <- rep(ymd_hms("2020-01-01 00:00:00.000"), length(files))
i = 565          
for(i in 1:length(files)){
  split <- NA
  hour < NA 
  min <- NA
  sec <- NA
  end <- NA
  part <- NA
  
  split <- strsplit(files[i], split = "_")
  year <- 2017
  month <- as.numeric(split[[1]][4])
  day <- as.numeric(split[[1]][5])
  hour <- as.numeric(split[[1]][6])
  min <- as.numeric(split[[1]][7])
  sec <- as.numeric(split[[1]][8])
  
  end <- (split[[1]][length(split[[1]])])
  part <- as.numeric(substr(end, 1, nchar(end)-4))
  
  buzz_times[i] <- 
    ymd(paste0(year,"-",month, "-", day))+hours(hour)+minutes(min)+
    seconds(sec)+seconds((part-1)/2)
}
```

## add buzz to acc
```{r}
buzz_times <- na.omit(buzz_times)
m17_60$buzz <- 0
i = 1
for(i in 1:length(buzz_times)){
  idx <- which.min(abs(m17_60$datetime-(buzz_times[i]-7*3600)))
  m17_60$buzz[idx:(idx+25)] <- 1
}


with(m17_60, plot(datetime, buzz))
with(m17_60[10000:100000,], 
     plot(datetime, ACCX, col = call+buzz+1, cex = call+buzz+1/2,  type = "o", pch = 16))

```

# save data
```{r}
save(m17_60, Mv18_main, Mv18_buzz, Mv18_cons, Mviv18, Mv18_summary, 
     file = "../../../../Dropbox/Vivesi2018/Analysis/Accelerometer/data/Mviv17_60_complete.robj")
load("../../../../Dropbox/Vivesi2018/Analysis/Accelerometer/data/Mviv17_60_complete.robj")

```

# write csv
```{r}
write.csv(m17_60, file = "../../../../Dropbox/VivesiACC/data/clean/Audio/Mviv17_60_ACC_Call.csv")
```

```{r}
hm() %>% 
```

